# PID of current job: 806
mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "GroupPQN", "NULL", "AutoNorm", "0", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-UpdateLoadingCmpd(mSet, "Ferulate")
mSet<-PlotCmpdSummary(mSet, "Ferulate", meta="NA",  meta2 = 0, format = "png", dpi = 72, width=NA)
mSet<-PLSDA.CV(mSet, "5", 5,5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_1_", "png", 72, width=NA)
mSet<-RF.Anal(mSet, 500,7,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_0_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_0_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_0_", "png", 72, width=NA)
mSet<-RF.Anal(mSet, 5000,7,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_1_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_1_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_1_", "png", 72, width=NA)
mSet<-SaveTransformedData(mSet)