# PID of current job: 429
mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "SumNorm", "NULL", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "3-PP")
mSet<-PlotCmpdSummary(mSet, "3-PP", meta="NA",  meta2 = 0, format = "png", dpi = 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-PlotCmpdSummary(mSet, "3-PP", meta="NA",  meta2 = 1, format = "png", dpi = 72, width=NA)
mSet<-PlotCmpdSummary(mSet, "3-PP", meta="NA",  meta2 = 2, format = "png", dpi = 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_1_", "feature", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "spearman", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_2_", "feature", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "spearman", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_3_", "feature", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_4_", "feature", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "spearman", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_5_", "feature", "png", 72, width=NA)
mSet<-PlotCmpdSummary(mSet, "3-PP", meta="NA",  meta2 = 3, format = "png", dpi = 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "3-2-1-3")
mSet<-PlotCorr(mSet, "ptn_6_", "feature", "png", 72, width=NA)
mSet<-FeatureCorrelation(mSet, "spearman", "Endotoxin")
mSet<-PlotCorr(mSet, "ptn_7_", "feature", "png", 72, width=NA)
mSet<-SaveTransformedData(mSet)